### PR TITLE
Update IMPORTANT_BEAR_LIST until CSS

### PR DESCRIPTION
**Pull request by sils1297**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
What do you mean until css?

**Comment by sils1297** [comment]
well all languages alphabetical up until css of course!

**Comment by Adrianzatreanu** [comment]
What about python, js, java? :p

**Comment by sils1297** [comment]
they were there before!

**Comment by Adrianzatreanu** [comment]
ack 26129dae715069a65da9f60e44d3b98c18abb4d4

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
