### PR TITLE
Add requirements.txt

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by Adrianzatreanu** [comment]
do we also need the bears? or is it just coala for now?

**Comment by sils1297** [comment]
not sure, let's take them, then don't list coala as dependency, coala-bears
will atomatically pull that in

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-03 11:36 GMT+01:00 Zatreanu Adrian-Gabriel <notifications@github.com

**Comment by Adrianzatreanu** [comment]
so basically i should get the coala-bears requirements.txt, as this will pull coala too?

**Comment by sils1297** [comment]
yeah

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-03-03 11:41 GMT+01:00 Zatreanu Adrian-Gabriel <notifications@github.com

**Pull request closed without merging**
