### PR TITLE
Add circleCI test command

### PR DESCRIPTION
**Pull request by Adrianzatreanu**

### CODE REVIEW

**Comment by sils1297** [comment]
please amend and repush, circle will build now. I guess it'll fail as you don't install requirements manually?

**Comment by Adrianzatreanu** [comment]
should i manually add the commands manually or we merge it like that?

**Comment by sils1297** [comment]
@Adrianzatreanu you wanna merge a PR that fails tests?

**Comment by Adrianzatreanu** [comment]
now that you put it like that, probably not. but how do we fix this? we add the commands to it like i said or?

**Comment by Adrianzatreanu** [comment]
closing this as @Redridge did it in the meantime

**Pull request closed without merging**
