### PR TITLE
.gitignore: Add it

### PR DESCRIPTION
**Pull request by Adrianzatreanu**
this will at least double the number of files for this project right now ;p

### CODE REVIEW

**Comment by sils1297** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
:(

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by sils1297** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
gl, rultor !

**Comment by Adrianzatreanu** [comment]
screw you, rultor !

**Comment by sils1297** [comment]
@rultor merge

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Comment by sils1297** [comment]
@Adrianzatreanu you know you need to rebase this?

**Comment by sils1297** [comment]
github doesn't show that because we have no CI statuses that are required.

**Comment by Adrianzatreanu** [comment]
ive read, im rebasing this now. thought i did

**Comment by Adrianzatreanu** [comment]
@rultor merge

**Pull request merged**
